namespace SentinelGate.ThreatDetection.Service.Services;

/// <summary>
/// Simple IP geolocation service using static mappings for demo purposes.
/// </summary>
public class GeoLookupService
{
    private static readonly Dictionary<string, string> IpCountryMap = new()
    {
        // US ranges
        { "1.", "US" },
        { "2.", "US" },
        { "3.", "US" },
        { "4.", "US" },
        { "8.", "US" },
        { "12.", "US" },
        { "13.", "US" },
        { "15.", "US" },
        { "16.", "US" },
        { "17.", "US" },
        { "18.", "US" },
        { "20.", "US" },
        { "24.", "US" },
        { "32.", "US" },
        { "34.", "US" },
        { "35.", "US" },
        { "38.", "US" },
        { "40.", "US" },
        { "44.", "GB" },
        { "45.", "GB" },
        { "46.", "SE" },
        { "47.", "CA" },
        { "49.", "DE" },
        { "50.", "US" },
        { "51.", "GB" },
        { "52.", "MX" },
        { "54.", "AR" },
        { "55.", "BR" },
        { "56.", "CL" },
        { "57.", "CO" },
        { "58.", "JP" },
        { "59.", "JP" },
        { "60.", "JP" },
        { "61.", "AU" },
        { "62.", "DE" },
        { "63.", "PH" },
        { "64.", "US" },
        { "65.", "SG" },
        { "66.", "US" },
        { "67.", "US" },
        { "68.", "US" },
        { "69.", "US" },
        { "70.", "US" },
        { "71.", "US" },
        { "72.", "US" },
        { "74.", "US" },
        { "76.", "US" },
        { "77.", "FR" },
        { "78.", "FR" },
        { "79.", "IT" },
        { "80.", "DE" },
        { "81.", "DE" },
        { "82.", "DE" },
        { "83.", "FR" },
        { "84.", "DE" },
        { "85.", "FR" },
        { "86.", "CN" },
        { "87.", "FR" },
        { "88.", "FR" },
        { "89.", "NL" },
        { "90.", "TR" },
        { "91.", "IN" },
        { "92.", "FR" },
        { "93.", "GB" },
        { "94.", "GB" },
        { "95.", "RU" },
        { "96.", "US" },
        { "97.", "US" },
        { "98.", "US" },
        { "99.", "US" },
        { "100.", "US" },
        { "101.", "IN" },
        { "103.", "IN" },
        { "104.", "US" },
        { "110.", "JP" },
        { "111.", "CN" },
        { "112.", "CN" },
        { "113.", "CN" },
        { "114.", "KR" },
        { "115.", "KR" },
        { "116.", "CN" },
        { "117.", "CN" },
        { "118.", "CN" },
        { "119.", "KR" },
        { "120.", "CN" },
        { "121.", "KR" },
        { "122.", "CN" },
        { "123.", "CN" },
        { "124.", "CN" },
        { "125.", "KR" },
        { "126.", "JP" },
        { "127.", "US" }, // loopback
        { "128.", "US" },
        { "130.", "US" },
        { "131.", "US" },
        { "132.", "US" },
        { "133.", "JP" },
        { "140.", "JP" },
        { "141.", "DE" },
        { "142.", "CA" },
        { "150.", "AU" },
        { "151.", "AU" },
        { "152.", "US" },
        { "155.", "US" },
        { "157.", "US" },
        { "160.", "US" },
        { "168.", "US" },
        { "169.", "US" },
        { "170.", "BR" },
        { "172.", "US" },
        { "173.", "US" },
        { "176.", "RU" },
        { "177.", "BR" },
        { "178.", "RU" },
        { "180.", "AU" },
        { "185.", "RU" },
        { "186.", "BR" },
        { "187.", "BR" },
        { "188.", "RU" },
        { "189.", "BR" },
        { "190.", "CO" },
        { "191.", "BR" },
        { "192.", "US" },
        { "193.", "DE" },
        { "194.", "NL" },
        { "195.", "SE" },
        { "196.", "ZA" },
        { "197.", "ZA" },
        { "198.", "US" },
        { "199.", "US" },
        { "200.", "BR" },
        { "201.", "MX" },
        { "202.", "AU" },
        { "203.", "AU" },
        { "204.", "US" },
        { "205.", "US" },
        { "206.", "US" },
        { "207.", "US" },
        { "208.", "US" },
        { "209.", "US" },
        { "210.", "JP" },
        { "211.", "KR" },
        { "212.", "DE" },
        { "213.", "ES" },
        { "216.", "US" },
        { "217.", "GB" },
        { "218.", "CN" },
        { "219.", "KR" },
        { "220.", "AU" },
        { "221.", "CN" },
        { "222.", "CN" },
        { "223.", "CN" },
        { "10.", "PRIVATE" },
    };

    /// <summary>
    /// Returns the country code for the given IP address.
    /// Uses static prefix matching for demo purposes.
    /// </summary>
    public string GetCountry(string ipAddress)
    {
        if (string.IsNullOrWhiteSpace(ipAddress))
            return "UNKNOWN";

        // Try matching by first octet prefix
        var firstDotIndex = ipAddress.IndexOf('.');
        if (firstDotIndex > 0)
        {
            var prefix = ipAddress[..(firstDotIndex + 1)];
            if (IpCountryMap.TryGetValue(prefix, out var country))
                return country;
        }

        return "UNKNOWN";
    }
}
